#!/bin/bash

function wait_on_x()
{
  echo "Waiting on $1"
  sleep $2
}

echo "This might take some minutes, sit back and relax with a beverage"

# Stop the running containers
docker stop elasticsearch server tester web

# Remove them
docker rm elasticsearch server tester web

# Pull in latest version
docker pull elasticsearch:2.4.4
docker pull nikita5/noark5-tester
docker pull hioaabi/nikita-noark5-core
docker pull nikita5/web

# Get elasticsearch up
docker run --name=elasticsearch -d -p 9200:9200 elasticsearch:2.4.4 -Des.network.host=0.0.0.0
wait_on_x elasticsearch 10
curl http://localhost:9200
curl -XPUT 'localhost:9200/_template/replicate_template' -d '{ "template" : "*", "settings" : {"number_of_replicas" : 0 } }'

# Get the main application up
if [[ `uname` == "Darwin" ]]; then
  docker run --name=server -d --network="host" --add-host=moby:127.0.0.1 hioaabi/nikita-noark5-core
else
  docker run --name=server -d --network="host" --add-host=`hostname`:127.0.0.1 hioaabi/nikita-noark5-core
fi
wait_on_x server 45

# Run test
docker run --name=tester --network="host" --add-host=`hostname`:127.0.0.1 nikita5/noark5-tester

# Run web UI
docker run --name=web -d -p 3000:3000 nikita5/web
